CC = gcc
CFLAGS = -std=gnu99 -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-align -Wcast-qual -Wjump-misses-init -Wundef -O2

rdpci:

.PHONY: clean
clean:
	rm -f rdpci
